version: CI Build {Build}
skip_commits:
  files:
  - .github/*
  - .github/*/*
  - docs/*
  - docs/*/*
  - docs/*/*/*
  - src/Documents/*
  - src/Documents/*/*
  - src/Documents/*/*/*
  - Scripts/*
  - .github/CONTRIBUTING.md
  - .github/FUNDING.md
  - .github/ISSUE_TEMPLATE.md
  - CODE_OF_CONDUCT.md
  - License.md
  - Logo.png
  - Readme.md
image: Visual Studio 2019
configuration:
- Debug
- Release
platform:
- x86
- x64
build:
  project: NSudo.sln
  verbosity: normal
after_build:
- >-
    7z a -r NSudo_CI_Build_%APPVEYOR_BUILD_NUMBER%.zip %APPVEYOR_BUILD_FOLDER%\src\Native\Output\*.exe

    7z a -r NSudo_CI_Build_%APPVEYOR_BUILD_NUMBER%.zip %APPVEYOR_BUILD_FOLDER%\src\Native\Output\*.dll

    7z a -r NSudo_CI_Build_%APPVEYOR_BUILD_NUMBER%.zip %APPVEYOR_BUILD_FOLDER%\src\Native\Output\*.pdb

    7z a -r NSudo_CI_Build_%APPVEYOR_BUILD_NUMBER%.zip %APPVEYOR_BUILD_FOLDER%\src\Native\Output\*.json
artifacts:
- path: NSudo_CI_Build_%APPVEYOR_BUILD_NUMBER%.zip
